boiler_t_prediction:
  home_t_dispersion_coefficient: 0.97
  homes_deltas_path: ../storage/homes_time_delta.csv
  optimized_t_table_path: ../storage/optimized_t_table.pickle
  t_graph_path: ../storage/t_graph.csv
logging:
  datetime_format: '%Y-%m-%d %H:%M:%S'
  format: '[%(asctime)s] %(levelname)s - %(message)s'
  level: DEBUG
  path: ../logs/log.log
datetime_processing:
  boiler_control_timezone: Asia/Yekaterinburg
  request_datetime_patterns:
  - (?P<year>\d{4})-(?P<month>\d{1,2})-(?P<day>\d{1,2})\s(?P<hours>\d{1,2}):(?P<minutes>\d{2})
  - (?P<day>\d{1,2})\.(?P<month>\d{1,2})\.(?P<year>\d{4})\s(?P<hours>\d{1,2}):(?P<minutes>\d{2})
  response_datetime_patterns: '%Y-%m-%d %H:%M'
service:
  host: 0.0.0.0
  port: 270
weather_forecast_providing:
  server_address: https://lysva.agt.town/
  server_timezone: Asia/Yekaterinburg
  update_interval: 600
