import datetime

TIME_STEP = datetime.timedelta(0, 0, 0, 0, 3)  # 3 minutes

TIMESTAMP_COLUMN_NAME = "dTimeStamp"
WEATHER_T_COLUMN_NAME = "weather_t"
TIME_DELTA_COLUMN_NAME = "time_delta"
HOME_NAME_COLUMN_NAME = "home_name"
HOME_T_COLUMN_NAME = "home_t"
BOILER_NAME_COLUMN_NAME = "BOILER"
BOILER_OUT_PIPE_T_COLUMN_NAME = "t1"

SOFT_M_WEATHER_T_COLUMN_NAME = "temp"
SOFT_M_TIME_COLUMN_NAME = "time"
SOFT_M_DATE_COLUMN_NAME = "date"
