TIMESTAMP = "timestamp"
TIME_DELTA = "time_delta"
WEATHER_T = "weather_t"
HOME_NAME = "home_name"
BOILER = "BOILER"
REQUIRED_T_AT_HOME_IN = "required_t_at_home_in"
REQUIRED_T_AT_HOME_OUT = "required_t_at_home_out"

SOFT_M_TEMP_GRAPH_WEATHER_T = "t"
SOFT_M_TEMP_GRAPH_REQUIRED_T_AT_HOME_IN = "in_t"
SOFT_M_TEMP_GRAPH_REQUIRED_T_AT_HOME_OUT = "out_t"

SOFT_M_WEATHER_T = "temp"
SOFT_M_WEATHER_TIME = "time"
SOFT_M_WEATHER_DATE = "date"
