
TIMESTAMP_COLUMN_NAME = "dTimeStamp"
BOILER_COLUMN_NAME = "BOILER"
WEATHER_T_COLUMN_NAME = "weather_t"
HOME_T_COLUMN_NAME = "home_t"
TIME_DELTA_COLUMN_NAME = "time_delta"
HOME_NAME_COLUMN_NAME = "home_name"
BOILER_T_COLUMN_NAME = "t1"
NTC_COLUMN_NAME = "nTC"

SOFT_M_WEATHER_T_COLUMN_NAME = "temp"
SOFT_M_TIME_COLUMN_NAME = "time"
SOFT_M_DATE_COLUMN_NAME = "date"
